### ISSUE TITLE
Does it work with System.import()?

### ISSUE THREAD

**Issue by unional** [mavericken/one-plugin#2]
Hi,

First of all, thank you for making this package.
I'm trying to use it on [domture](https://github.com/unional/domture).
I uses `systemjs.import()` to load the files.

Loading `*.ts` files without extension is fine, but it still fails on loading `js` and `tsx` files.

The config is roughly like this:
```ts
{
      map: {
        'app': rootDir
      },
      packages: {
        'app': {
          defaultExtension: false,
          meta: {
            '*': {
              oneOptions: {
                meta: {
                  '*.ts': {
                    loader: 'plugin-typescript'
                  },
                  '*.tsx': {
                    loader: 'plugin-typescript'
                  },
                  '*.js': {}
                }
              },
              loader: 'one-plugin'
            }
          }
        },
        'typescript': {
          'main': 'lib/typescript.js',
          'meta': {
            'lib/typescript.js': {
              'exports': 'ts'
            }
          }
        },
        'plugin-typescript': {
          'main': 'lib/plugin.js'
        }
      },
      transpiler: 'plugin-typescript'
    }
  }
```

Do you think `one-plugin` support `systemjs.import()` usage or there may be something wrong in the config?

Here is a repro on that project:
https://github.com/unional/domture/tree/one-plugin
The configuration is done here: https://github.com/unional/domture/blob/one-plugin/src/systemjsConfig.ts#L43

The test cases that fails are here: https://github.com/unional/domture/blob/one-plugin/src/createDomture.ts.spec.ts#L94-L119

**Comment by mavericken** [comment]
I'm getting 404 errors on all of your links.

However, I might not be able to properly support you on this anyways, considering I have been out of node.js development for several months.

I tested SystemJS.import in the experimental branch, and it worked for me with and without bundling (though in the bundle it would just grab the file the old fashioned way the way I have it setup, but maybe it would grab it from the bundle if it was included in the bundle):
https://github.com/mavericken/one-plugin/blob/experimental/examples/jspm/app/main.js#L7
![image](https://user-images.githubusercontent.com/7833752/33489719-af3dbfc0-d682-11e7-828c-fed36722d62c.png)

My expectation is that you are using a newer version of SystemJS than what I developed this with (SystemJS v0.19.41), and I recall that SystemJS was in the middle of large changes to the module loading, so it may take some work to update one-plugin to support it.

**Comment by unional** [comment]
Yes, likely that is part of the issue. I am using systemjs 0.20.19. And there are some breakages between the two.

For my situation, I probably need to come up with a different plugin to properly do the node resolution, e.g. I need to support https://github.com/unional/domture/issues/34

Thanks again.
